version: "3.6"
services:
  fpm7.2:
    image: sonrac/infomir-php:php-fpm-7.2
    volumes:
      - "./:/home/infomir/site"
    environment:
      - PROJECT_DIR_ROOT=/home/infomir/site
      - COMPOSER_HOME=/tmp
      - XDEBUG_ENABLE=1
      - XDEBUG_CLI_ENABLE=1
    working_dir: /home/infomir/site
